"""Provenance Guard — Flask API.

Detects whether a piece of text was written by a human or generated by AI by
combining a Groq LLM signal with stylometric heuristics. Exposes endpoints to
submit text for classification, appeal a classification, and read the audit log.
"""

import json
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from audit import read_log, write_log
from scoring import combine_scores, get_label
from signals import groq_signal, stylometric_signal

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    storage_uri="memory://",
)


def _attribution_from_confidence(confidence):
    """Map a confidence value onto a machine-readable attribution string.

    Mirrors the thresholds used by ``scoring.get_label`` but returns the short
    codes stored in the audit log and API responses:
    ``likely_ai``, ``uncertain``, or ``likely_human``.
    """
    if confidence >= 0.70:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute; 100 per day")
def submit():
    """Classify submitted text as human- or AI-written.

    Expects a JSON body ``{"text": "...", "creator_id": "..."}``. Both fields
    are required (returns 400 otherwise). Runs both detection signals, combines
    them into a confidence value, derives an attribution and label, writes the
    result to the audit log, and returns the classification.
    """
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not creator_id:
        return jsonify({"error": "Both 'text' and 'creator_id' are required."}), 400

    groq_score = groq_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = combine_scores(groq_score, stylo_score)
    label = get_label(confidence)
    attribution = _attribution_from_confidence(confidence)
    content_id = str(uuid.uuid4())

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "groq_score": groq_score,
        "stylo_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "groq_score": groq_score,
        "stylo_score": stylo_score,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    """Register an appeal against a prior classification.

    Expects a JSON body ``{"content_id": "...", "creator_reasoning": "..."}``.
    Looks up the entry by ``content_id`` (returns 404 if not found), updates its
    status to ``under_review`` and records the supplied reasoning, then rewrites
    the audit log.
    """
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    if not content_id or not creator_reasoning:
        return jsonify(
            {"error": "Both 'content_id' and 'creator_reasoning' are required."}
        ), 400

    entries = read_log()
    found = False
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = creator_reasoning
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found."}), 404

    with open("audit_log.json", "w") as f:
        json.dump(entries, f, indent=2)

    return jsonify({
        "message": "Appeal received. Your submission is now under review.",
        "content_id": content_id,
    })


@app.route("/log", methods=["GET"])
def log():
    """Return all audit log entries as ``{"entries": [...]}``."""
    return jsonify({"entries": read_log()})


if __name__ == "__main__":
    app.run(debug=True)
