"""Detection signals for Provenance Guard.

Provides two independent signals that estimate whether a piece of text was
written by a human or generated by an AI model:

- ``groq_signal``: an LLM-based judgment via the Groq API.
- ``stylometric_signal``: lightweight, dependency-free stylometric heuristics.

Both signals return a float in the range 0.0 (definitely human) to 1.0
(definitely AI).
"""

import json
import os
import string

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"


def groq_signal(text):
    """Ask the Groq LLM to judge whether ``text`` reads as human or AI.

    Sends the text to Groq with a prompt instructing it to return only a JSON
    object of the form ``{"score": 0.82, "reasoning": "..."}`` where ``score``
    ranges from 0.0 (definitely human) to 1.0 (definitely AI).

    Returns the parsed score as a float. If anything goes wrong (network error,
    malformed JSON, missing key), returns 0.5 as a safe, neutral default.
    """
    prompt = (
        "You are a forensic text analyst. Assess whether the following text "
        "reads as human-written or AI-generated.\n\n"
        "Respond with ONLY a JSON object in exactly this form, with no extra "
        'text, no markdown, and no code fences:\n'
        '{"score": 0.82, "reasoning": "..."}\n\n'
        "The score must be a float from 0.0 (definitely human) to 1.0 "
        "(definitely AI). The reasoning must be a short explanation.\n\n"
        f"Text to analyze:\n{text}"
    )

    try:
        client = Groq(api_key=os.environ["GROQ_API_KEY"])
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)
        return float(parsed["score"])
    except Exception:
        return 0.5


def stylometric_signal(text):
    """Estimate AI-likeness from pure-Python stylometric heuristics.

    Computes three metrics, each contributing to an overall AI-likeness score:

    1. Sentence length variance — AI text tends toward uniform sentence
       lengths (low variance). High uniformity raises the score.
    2. Type-token ratio — unique words divided by total words. AI text reuses
       vocabulary more, so a lower ratio raises the score.
    3. Punctuation density — punctuation characters divided by total
       characters. AI text tends to be sparser/cleaner, so very low density
       slightly raises the score.

    The three metrics are combined into a single float from 0.0 to 1.0 and
    returned.
    """
    if not text or not text.strip():
        return 0.5

    # --- Metric 1: sentence length uniformity ---
    sentences = [s.strip() for s in _split_sentences(text) if s.strip()]
    if len(sentences) >= 2:
        lengths = [len(s.split()) for s in sentences]
        mean_len = sum(lengths) / len(lengths)
        variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        std_dev = variance ** 0.5
        # Coefficient of variation: lower spread => more uniform => more AI-like.
        cv = std_dev / mean_len if mean_len > 0 else 0
        uniformity_score = max(0.0, min(1.0, 1.0 - cv))
    else:
        # Not enough sentences to judge variance; stay neutral.
        uniformity_score = 0.5

    # --- Metric 2: type-token ratio ---
    words = [w.strip(string.punctuation).lower() for w in text.split()]
    words = [w for w in words if w]
    if words:
        ttr = len(set(words)) / len(words)
        # Lower diversity => more repetition => more AI-like.
        ttr_score = max(0.0, min(1.0, 1.0 - ttr))
    else:
        ttr_score = 0.5

    # --- Metric 3: punctuation density ---
    total_chars = len(text)
    if total_chars > 0:
        punct_count = sum(1 for c in text if c in string.punctuation)
        density = punct_count / total_chars
        # Typical human prose sits around ~3% punctuation. Treat that as the
        # reference: very low density nudges the score up.
        reference = 0.03
        density_score = max(0.0, min(1.0, (reference - density) / reference))
    else:
        density_score = 0.5

    # --- Combine: weighted average of the three metrics ---
    combined = 0.4 * uniformity_score + 0.4 * ttr_score + 0.2 * density_score
    return round(max(0.0, min(1.0, combined)), 4)


def _split_sentences(text):
    """Split ``text`` into sentences on '.', '!' and '?' boundaries.

    A small, dependency-free splitter used by ``stylometric_signal``. Returns a
    list of raw sentence strings (callers strip and filter empties).
    """
    sentences = []
    current = []
    for char in text:
        current.append(char)
        if char in ".!?":
            sentences.append("".join(current))
            current = []
    if current:
        sentences.append("".join(current))
    return sentences
